version: "3.9"

services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter_proyecto_gestion
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./requirements.txt:/tmp/requirements.txt
    command: >
      bash -c "
      pip install --no-cache-dir -r /tmp/requirements.txt &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
      "
